### ISSUE TITLE
mesa: on release 23.3.0, drop LLVM requirement

### ISSUE THREAD

**Issue by apprehensions** [echawk/kiss-xorg#154]
https://codeberg.org/kiss-community/repo/issues/173

https://docs.mesa3d.org/release-calendar.html

**Comment by ehawkvu** [comment]
I'm likely to follow whatever upstream decides btw - I'm definitely in favor of removing the llvm dependency from mesa though.

**Comment by echawk** [comment]
Resolved as of: d302e67
