### ISSUE TITLE
FIrefox 131 failing to build with rust 1.82 fix

### ISSUE THREAD

**Issue by Ivyfri** [echawk/kiss-xorg#163]
There is an open [issue](https://codeberg.org/kiss-community/repo/issues/202) in main repo about it, seems like rust patch and firefox version bump fixed it. Can we get firefox 133.0b9 in testing as well?

**Comment by echawk** [comment]
@Ivyfri I can see about pushing something tomorrow - in that thread it looks like Rohan also says that the testing build for 133.0b9 also fails?

**Comment by Ivyfri** [comment]
True, i just tried to build firefox 133 with build script from this repo and it failed with same error. I guess its purely up to main repo to solve it now since llvm and rust packages are there.  Still having firefox 133.0b9 in testing would be nice when issue will be resolved.

**Comment by Ivyfri** [comment]
Well, trurns out it was not related to firefox version at all so it has nothing to do with this repo, closing.
